<?php foreach ($this->orderNumbers as $orderNumber){ 
    $rowcount=count($this->picklist[$orderNumber]['lines']);
    if ($rowcount > 12) {
        $pages = ceil(($rowcount-12)/15) +1;
    } else {
        $pages = ceil($rowcount/12);
    }
    $y = 0;
    $page = 1;
    $sumweight =0;
    $sumitem =0;
    ?>
    <?php if (in_array($orderNumber,$this->barcodes)){ 
         echo $this->partial('/partials/portal/printbarcode.phtml', array(
                    "orderNumber" => $orderNumber, 
                    "header" => $this->barcodes[$orderNumber]['header'][0] ,
                    "list" => $this->barcodes[$orderNumber]['lines'] ,
                    
                ));  ?>
    <?php }         
    if (array_key_exists( $orderNumber,$this->picklist)) { ?>
        <div class="pdf" >
            <?php echo $this->partial('/partials/portal/picklistheader.phtml', array(
                    "orderNumber" => $orderNumber, 
                    "picklist" => $this->picklist ,
                    "top" => 1,
                    "allpages" => $pages,
                    "page" => $page,
                ));  ?>
            <table  class='picking' >                        
                <tr>
                    <th class="table-header cols">Qty. Shipped   </th>
                    <th class="table-header colm">Item Number</th>
                    <th class="table-header coll">Description</th>
                    <th class="table-header colm">Item UPC</th>
                    <th class="table-header cols">Qty</th>
                    <th class="table-header cols">Weight</th>
                </tr>
                <?php foreach($this->picklist[$orderNumber]['lines'] as $pick) { $y++; 
                        $sumweight = $sumweight + $pick['weight']*$pick['QtyIssued'];
                        $sumitem = $sumitem + $pick['QtyIssued'];
                        ?> 
                    <tr>
                        <td class="table-line cols"><?php echo $pick['QtyIssued']; ?></td>
                        <td class="table-line colm">
                            <table style="width:120px">
                                <tr >
                                    <td style="border:0px;padding:0px; margin: 0px; text-align: left;width: 100%;"><?php echo $pick['ItemKey']; ?></td>
                                </tr>
                                <tr >
                                    <td style="border:0px;padding:0px; margin: 0px;text-align: right;width: 100%"><?php echo $pick['binno']; ?></td>
                                </tr>
                            </table>                        
                        </td>
                        <td class="table-line coll" style="display: block">
                            <table style="padding:0px; margin: 0px;" >
                                <tr >
                                    <td colspan=2 style="border:0px;padding:0px; margin: 0px;"><?php echo substr(trim($pick['Description']), 0,47); ?></td>
                                </tr>
                                <tr>
                                    <td style="border:0px;padding:0px; margin: 0px;"><?php echo $pick['lotno']; ?></td>
                                    <td style="border:0px;padding:0px; margin: 0px; text-align: right;"><?php echo $pick['exp_date']; ?></td>
                                </tr>
                            </table> 
                        </td>
                        <td class="table-line colm" ><?php echo $pick['UPC']; ?></td>
                        <td class="table-line cols" ><?php echo $pick['QtyOrd']; ?></td>
                        <td class="table-line cols" ><?php echo $pick['weight']; ?></td>    
                    </tr>  
            <?php  

            if($page == 1 ) $records_count  =   12;
            else if($page>1) $records_count  =   15; 

            if ($y % $records_count == 0 ) {     
                        $y=0;
                        $page++;
                        ?>
                    </table>
                    </div>  
                    <div class="cleard"></div>  
                    <div class="pdf" >
                        <div class="pdfrow" >Page <?php echo $page; ?> of <?php echo $pages; ?></div>
                        <div class="pdfrow" >
                            <div class="pdfcolumn">
                                <span class="bold"> Jarrow Formulas Inc </span>
                                1824 S. Robertson Blvd
                                Los Angeles CA 90035
                                USA
                                310-204-6936
                                310-204-5261
                            </div>
                            <div class="pdfcolumnwide bold">Packing Slip</div>
                            <div class="pdfcolumn center"> 
                                <span class="bold">Date</span> <br>
                                <?php echo date('m/d/y'); ?> <br><br>
                                <img style="display: block;margin-left: auto;margin-right: auto;" src="<?php echo  '\pdf\barcode_'.$orderNumber.'.png'; ?> "/>
                                <span><?php echo $orderNumber; ?> </span>
                            </div>
                        </div>
                        <div class="cleard"></div>      
                        <?php $header = $this->picklist[$orderNumber]['header'][0]; ?>  
                            <table  class='picking' >
                                <tr>
                                    <th class="table-header"> Customer No. <br>  <?php echo $header['custkey']; ?></th>
                                    <th class="table-header">PO Number <br>  <?php echo $header['po_number']; ?></th>
                                    <th class="table-header">Terms <br>  <?php echo $header['Terms']; ?></th>
                                    <th class="table-header">CSA <br>  <?php echo $header['CSA']; ?></th>
                                    <th class="table-header">Ship Via <br>  <?php echo $header['Ship_Via']; ?></th>
                                    <th class="table-header">Ship Date <br>  <?php echo $header['ord_date']; ?></th>
                                </tr>
                            </table> 
                            <div class="pdfrow" >
                                <span class="bold">Category  </span><?php echo $header['category']; ?>
                            </div>  

                        <div class="cleard"></div>
                        <table  class='picking' >                        
                            <tr>
                                <th class="table-header cols">Qty. Shipped   </th>
                                <th class="table-header colm">Item Number</th>
                                <th class="table-header coll">Description</th>
                                <th class="table-header colm">Item UPC</th>
                                <th class="table-header cols">Qty. Ordered</th>
                                <th class="table-header cols">Weight</th>
                            </tr>
                    <?php  
            } 
        }  ?>
          </table>
        </div>     
        <div class="pdfrow bottom"  >
            <table>
                <tr>
                    <td>Shipping Instruction:</td>
                </tr>
                <tr>
                    <td colspan="2">Picked by :_________________________________________</td>
                    <td >Total weight : <?php echo $sumweight; ?></td>
                    <td>Total Items :  <?php echo $sumitem; ?></td>
                </tr>
                <tr>
                    <td colspan="2">Packed by :________________________________________</td>
                    <td colspan="2"> Total Packages :________________________________ </td>
                </tr>
                <tr>    
                    <td >Received by :___________</td>
                    <td >Received Date :___________</td>
                    <td colspan="2">Cases Received :________________________________ </td>
                </tr>
            </table>
        </div>
        <div class="cleard"></div>
    <?php } ?> 
<?php } ?>

