<form action="" method="post">
<table class="portal_table" id="scan_table">
    <tr>
        <td colspan='6' class="top-header">Filter Orders</td>
    </tr>
    <tr>
        <td class="form-header">Order Number</td>
        <td class="form-header">Customer Number</td>
        <td class="form-header">Ship Via</td>
        <td class="form-header">Order Category</td>
        <td class="form-header">Order Date</td>
        <td class="form-header">Probiotics</td>
        <td class="form-header"></td>
    </tr>
    <tr>
        <td class="form-field"><input class="form-element" type="text" name="order_number" id="order_number" value=""></td>
        <td class="form-field"><input class="form-element" type="text" name="customer_number" id="customer_number" value=""></td>
        <td class="form-field"><input class="form-element" type="text" name="Ship_Via" id="Ship_Via" value=""></td>
        <td class="form-field"><input class="form-element" type="text" name="Order_Category" id="Order_Category" value=""></td>
        <td class="form-field"><input class="form-element" type="text" name="Order_date" id="Order_date" value=""></td>
        <td class="form-field">
            <select  class="form-element" name="Has_Probo" id="Has_Probo" style="width: 100%;">
                <option value="">...</option>
                <option value="0">No</option>
                <option value="1">Yes</option>
            </select>
        </td>
        <td class="form-field">
            <input type="submit" name="submit" id="submit" value="Search">
        </td>
    </tr>
</table>
</form>
<table class="portal_table" style="margin-top: 10px;">
    <thead>
        <tr>
            <td colspan='20' style="text-align: center;"class="top-header">Released Orders</td>
        </tr>
        <tr>
            <td colspan="20"><?php echo $this->pagination; ?></td>
        </tr>
        <tr>
            <td colspan='20'  style="cursor:pointer; text-align:right" class="printAll">Print All</td>
        </tr>
        <tr>
            <th class="form-header">#</th>
            <th class="form-header">Order no</th>
            <th class="form-header">Customer Number</th>
            <th class="form-header">Customer Name</th>
            <th class="form-header">Payment terms</th>
            <th class="form-header">Ship Via</th>
            <th class="form-header">Order Category</th>
            <th class="form-header">No Items</th>
            <th class="form-header">Total Qty</th> 
            <th class="form-header">Has Probo</th>
            <th class="form-header">Order Date</th>
            <th class="form-header">State</th>
            <th class="form-header">Zipcode</th>
            <th class="form-header">CSA</th>
            <!--<th class="form-header">Notes</th>-->
            <th class="form-header">ERP Printed</th>
            <th class="form-header">Printed</th>
            <th class="form-header printlabel">Barcode
                <div id="notification" style="display: none;">
                    Select one
                    <span class="dismiss"><a title="dismiss this notification">x</a></span>
                </div>
            </th>
            <th class="form-header printlabel">Picklist</th>
            <th class="form-header">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $i = 1;
        foreach ($this->entries as $entry){
            $c1 = '';
            $c2 = '';

            if ($entry['Order_Category'] != $entry['Customer_Cat']) {
                $c1 = 'red';
            }
            if ($entry['Ship_Via'] != $entry['Customer_Ship']) {
                $c2 = 'red';
            }

            if ($entry['Has_Probo'] == 1) {
                $prob = 'Yes';
            } else {
                $prob = 'No';
            }
            ?>
            <tr id="<?php echo $entry['Order_no']; ?>">
                <td class="form-field"><?php echo $i; ?></td>
                <td class="form-field"><?php echo $entry['Order_no']; ?></td>
                <td class="form-field"><?php echo $entry['customer_number']; ?></td>
                <td class="form-field"><?php echo $entry['customer_name']; ?></td>
                <td class="form-field"><?php echo $entry['Payment_terms']; ?></td>
                <td class="form-field <?php echo $c2; ?>"><?php echo $entry['Ship_Via']; ?></td>
                <td class="form-field <?php echo $c1; ?>"><?php echo $entry['Order_Category']; ?></td>
                <td class="form-field"><?php echo $entry['No_Items']; ?></td>
                <td class="form-field"><?php echo $entry['Total_Qty']; ?></td>
                <td class="form-field"><?php echo $prob; ?></td>
                <td class="form-field"><?php echo $entry['Order_date']; ?></td>
                <td class="form-field"><?php echo $entry['State']; ?></td>
                <td class="form-field"><?php echo $entry['Zip']; ?></td>
                <td class="form-field"><?php echo $entry['CSA']; ?></td>
                <td class="form-field" id="erp_printed_<?php echo $entry['Order_no']; ?>">
                    <?php if (in_array($entry['Order_no'], $this->sono)) {
                            echo "YES";
                        } ?>
                </td>
                <td class="form-field" id="printed_<?php echo $entry['Order_no']; ?>"><?php if($entry['UARPRN']==1){ echo 'YES'; } ?></td>
<!--                <td class="form-field <?php //if ($entry['Notes'] != '') echo 'notes';?>">
                    <?php //if ($entry['Notes'] != '') { ?>
                        Show Notes
                        <span class="tooltiptext"><?php// echo $entry['Notes']; ?></span>
                    <?php// } ?>
                </td>-->
                <td class="form-field"><input type="checkbox" class="printCheckBarcode" data-orderNumber="<?php echo $entry['Order_no']; ?>"></td>
                <td class="form-field"><input type="checkbox" class="printCheckPicklist" data-orderNumber="<?php echo $entry['Order_no']; ?>"></td>
                <td class="form-field">
                    <a target="_blank" >
                        <img src="\images\icons\famfam\printer.png" style="cursor:pointer;" class="pointer printOne" data-orderNumber="<?php echo $entry['Order_no']; ?>"/>
                    </a> 
                    <img src="\images\icons\famfam\arrow_right.png" style="cursor:pointer;" data-orderNumber="<?php echo $entry['Order_no']; ?>" class="pointer proceed"/>
                </td>			
            </tr>
    <?php $i++;
        } ?>
    </tbody>
</table>
<div class="modal"></div>

<script type="text/javascript">
//    setTimeout(function() {
//        location.reload();
//    }, 5 * 60 * 1000);
</script> 