<script type="text/javascript">
    $(document).ready(function() {
        $("#start_date,#end_date").datepicker(); 
    });
</script>
<form action="" method="post">
    <table id="form" >
        <tr>
            <td colspan=2 class="top-header"><?php echo $this->title; ?></td>
        </tr>
        <tr>
            <td class="form-element">Item number</td>
            <td class="form-element">Buyer</td>
            <!--<td class="form-element">Lot NUmber</td>-->
            <td class="form-element">Status</td>
            <td class="form-element">Start date</td>
            <td class="form-element">End Date</td>
            <td class="form-element"></td>
        </tr>    
        <tr>    
            <td class="form-element"><input type="text" name="item_number" value="<?php echo $this->entries['item_number']; ?>" id="item_number" /></td>
            <td class="form-element"><input type="text" name="buyer" value="<?php echo $this->entries['buyer']; ?>" id="buyer" /></td>
            <!--<td class="form-element"><input type="text" name="lot_number" value="<?php echo $this->entries['lot_number']; ?>" id="lot_number" /></td>-->
            <td class="form-element">
                <select name="status" id="status">
                    <option value="">All</option>
                    <option <?php if($this->entries['status'] == 'within_QC_window') echo 'selected="selected"';?> value="within_QC_window">Within QC window</option>
                    <option <?php if($this->entries['status'] == 'outside_QC_window') echo 'selected="selected"';?> value="outside_QC_window">Outside QC window</option>
                </select>
            <td class="form-element"><input type="text" name="start_date" value="<?php echo $this->entries['start_date']; ?>" id="start_date" /></td>
            <td class="form-element"><input type="text" name="end_date" value="<?php echo $this->entries['end_date']; ?>" id="end_date" /></td>
            <td colspan='2' class="form-element" style="text-align: center;">
                <input type="submit" name="submit" id="submit" value="Search">
            </td>
        </tr>

        <tr>
            
        </tr>
    </table>
</form>

<?php if(is_array($this->records) && count($this->records) > 0) {?> 
    <table class='picking'>
        <thead>                
            <tr>
                <th class="table-header">Item Number</th>
                <th class="table-header">Item Description</th>
                <th class="table-header">PO Number</th>
                <th class="table-header">WHSE</th>
                <th class="table-header">Supplier</th>
                <th class="table-header">LStatus</th>
                <th class="table-header">Order Qty</th>
                <th class="table-header">Conf Qty</th>
                <th class="table-header">Received Qty</th>
                <th class="table-header">Received Date</th>
                <th class="table-header">Qty Balance</th>
                <th class="table-header">UOM</th>
                <th class="table-header">PPrice</th>
                <th class="table-header">ReqDel Date</th>
                <th class="table-header">Confirmed Date</th>
                <th class="table-header">PrevConf Date</th>
                <th class="table-header">Entry Date</th>
                <th class="table-header">Chang Date</th>
                <th class="table-header">Buyer</th>
                <th class="table-header">QC Aging</th>
                <th class="table-header">STATUS</th>
            </tr>
        </thead>
        <tbody >
        <?php  foreach ($this->records as $entry) { ?>
                <tr>
                    <td class="table-line"><?php echo $entry['ITNO']; ?></td>
                    <td class="table-line"><?php echo $entry['ITDesc']; ?></td>
                    <td class="table-line"><?php echo $entry['PONum']; ?></td>
                    <td class="table-line"><?php echo $entry['WHSE']; ?></td>
                    <td class="table-line"><?php echo $entry['Supplier']; ?></td>
                    <td class="table-line"><?php echo $entry['LStatus']; ?></td>
                    <td class="table-line"><?php echo $entry['OrdQty']; ?></td>
                    <td class="table-line"><?php echo $entry['ConfQty']; ?></td>
                    <td class="table-line"><?php echo $entry['ReceivedQty']; ?></td>
                    <td class="table-line"><?php echo $entry['ReceivedDate']; ?></td>
                    <td class="table-line"><?php echo $entry['QtyBalance']; ?></td>
                    <td class="table-line"><?php echo $entry['UOM']; ?></td>
                    <td class="table-line"><?php echo $entry['PPrice']; ?></td>
                    <td class="table-line"><?php echo $entry['ReqDelDate']; ?></td>
                    <td class="table-line"><?php echo $entry['ConfirmedDate']; ?></td>
                    <td class="table-line"><?php echo $entry['PrevConfDate']; ?></td>
                    <td class="table-line"><?php echo $entry['EntryDate']; ?></td>
                    <td class="table-line"><?php echo $entry['ChangDate']; ?></td>
                    <td class="table-line"><?php echo $entry['Buyer']; ?></td>
                    <td class="table-line"><?php echo $entry['QCAging']; ?></td>
                    <td class="table-line"><?php echo $entry['STATUS']; ?></td>
                </tr>
        <?php  } ?>
        </tbody>
    </table>    
<?php } ?>
