<script type="text/javascript">
    $(document).ready(function() {
        $("#start_date,#end_date").datepicker(); 
    });
</script>
<form action="" method="post">
    <table id="form" style="margin:0 auto;">
        <tr>
            <td colspan=2 class="top-header">Shipment</td>
        </tr>
        <tr>
            <td class="form-element">Item Key</td>
            <td class="form-element"><input type="text" name="itemkey" value="<?php echo $this->entries['itemkey']; ?>" id="itemkey"  required="required"/></td>
        </tr>   
        <tr>
            <td class="form-element">Start date</td>
            <td class="form-element"><input type="text" name="start_date" value="<?php echo $this->entries['start_date']; ?>" id="start_date"  required="required"/></td>
        </tr>        
        <tr>
            <td class="form-element">End date</td>
            <td class="form-element"><input type="text" name="end_date" value="<?php echo $this->entries['end_date']; ?>" id="end_date"  required="required"/></td>
        </tr>        
        <tr>
            <td colspan='2' class="form-element" style="text-align: center;">
                <input type="submit" name="submit" id="submit" value="Search">
            </td>
        </tr>
    </table>
</form>

<?php // if(is_array($this->header) && count($this->header) > 0) {  ?> 
<?php if(is_array($this->records) && count($this->records) > 0) { 
    $prevId = 0;
    foreach ($this->records as $entry) { 
        if ($entry['orderId'] != $prevId) {?>
            <div style="
    border: 1px solid #000;">
            <table class='picking' >
               <thead>
                   <tr>
                       <th class="table-header">shipment Id</th>
                       <th class="table-header">order Id</th>
                       <th class="table-header">customer Email</th>
                       <th class="table-header">name</th>
                       <th class="table-header">company</th>
                       <th class="table-header">street1</th>
                       <th class="table-header">street2</th>
                       <th class="table-header">street3</th>
                       <th class="table-header">city</th>
                       <th class="table-header">state</th>
                       <th class="table-header">postalCode</th>
                       <th class="table-header">country</th>
                       <th class="table-header">phone</th>
                       <th class="table-header">residential</th>
                       <th class="table-header">addressVerified</th>
                   </tr>
               </thead>
               <tbody style="display:table-footer-group">
                   <tr id="<?php echo $entry['']; ?>">
                       <td class="table-line"><?php echo $entry['shipmentId']; ?></td>
                       <td class="table-line"><?php echo $entry['orderId']; ?></td>
                       <td class="table-line"><?php echo $entry['customerEmail']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_name']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_company']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_street1']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_street2']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_street3']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_city']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_state']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_postalCode']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_country']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_phone']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_residential']; ?></td>
                       <td class="table-line"><?php echo $entry['shipTo_addressVerified']; ?></td>
                   </tr>
               </tbody>
            </table>
            <table class='picking' >
               <thead>
                   <tr>
                       <th class="table-header">order ItemId</th>
                       <th class="table-header">line Item Key</th>
                       <th class="table-header">sku</th>
                       <th class="table-header">sku qty</th>
                       <th class="table-header">name</th>
                       <th class="table-header">image Url</th>
                       <th class="table-header">weight</th>
                       <th class="table-header">quantity</th>
                       <th class="table-header">unit Price</th>
                       <th class="table-header">tax Amount</th>
                       <th class="table-header">shipping Amount</th>
                       <th class="table-header">warehouse Location</th>
                       <th class="table-header">item options</th>
                       <th class="table-header">product Id</th>
                       <th class="table-header">fulfillment Sku</th>
                       <th class="table-header">adjustment</th>
                       <th class="table-header">upc</th>
                       <th class="table-header">create Date</th>
                       <th class="table-header">modify Date</th>
                   </tr>
               </thead>
               <tbody style="display:table-footer-group">
        <?php } ?>
                       <tr>
                           <td class="table-line"><?php echo $entry['orderItemId']; ?></td>
                           <td class="table-line"><?php echo $entry['lineItemKey']; ?></td>
                           <td class="table-line"><?php echo $entry['sku']; ?></td>
                           <td class="table-line" style="text-align: center"><?php echo $entry['skuqty']; ?></td>
                           <td class="table-line"><?php echo $entry['name']; ?></td>
                           <td class="table-line"><?php echo $entry['imageUrl']; ?></td>
                           <td class="table-line"><?php echo $entry['weight']; ?></td>
                           <td class="table-line"><?php echo $entry['quantity']; ?></td>
                           <td class="table-line"><?php echo $entry['unitPrice']; ?></td>
                           <td class="table-line"><?php echo $entry['taxAmount']; ?></td>
                           <td class="table-line"><?php echo $entry['shippingAmount']; ?></td>
                           <td class="table-line"><?php echo $entry['warehouseLocation']; ?></td>
                           <td class="table-line"><?php echo $entry['itemoptions']; ?></td>
                           <td class="table-line"><?php echo $entry['productId']; ?></td>
                           <td class="table-line"><?php echo $entry['fulfillmentSku']; ?></td>
                           <td class="table-line"><?php echo $entry['adjustment']; ?></td>
                           <td class="table-line"><?php echo $entry['upc']; ?></td>
                           <td class="table-line"><?php echo $entry['createDate']; ?></td>
                           <td class="table-line"><?php echo $entry['modifyDate']; ?></td>
                       </tr> 
    <?php if ($entry['orderId'] != $prevId) { 
            $prevId =$entry['orderId']; ?>
               </tbody>
            </table>
            </div>
    <?php  } 
    }
 } ?>
