<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <link rel="stylesheet" href="/css/global.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 60px;">
    
    <div id="header-navigation" >
        <ul class="menu">
            <li>
                <a href="<?php echo $this->url(
                    array('controller'=>'ticket',
                          'action'=>'tickets'),
                    'default',
                    true) ?>">Ticket</a>
            </li>
            <li>
                 <a href="<?php echo $this->url(
                    array('controller'=>'ticket',
                          'action'=>'inventories'),
                    'default',
                    true) ?>">Inventory</a>
            </li>
            <li>
                <a href="<?php echo $this->url(
                    array('controller'=>'ticket',
                          'action'=>'pickorders'),
                    'default',
                    true) ?>">Orders</a>
            </li>
            <li>
                 <a href="<?php echo $this->url(
                    array('controller'=>'ticket',
                          'action'=>'releasedorders'),
                    'default',
                    true) ?>">Release Orders</a>
            </li>
            <li>
                 <a href="<?php echo $this->url(
                    array('controller'=>'ticket',
                          'action'=>'pbon'),
                    'default',
                    true) ?>">Picklist by order number</a>
            </li>
            <li>
                 <a href="<?php echo $this->url(
                array('controller'=>'ticket',
                      'action'=>'report'),
                'default',
                true) ?>">Report</a>
            </li>
            <li>
               <a href="<?php echo $this->url(
                array('controller'=>'ticket',
                      'action'=>'por'),
                'default',
                true) ?>">Purchase Order Receipt </a>
            </li>
            <li>
               <a href="<?php echo $this->url(
                array('controller'=>'ticket',
                      'action'=>'shipment'),
                'default',
                true) ?>">Shipment </a>
            </li>
            <li>
               <a href="<?php echo $this->url(
                array('controller'=>'ticket',
                      'action'=>'aging'),
                'default',
                true) ?>">Aging Report </a>
            </li>
        </ul>
        
       
        
       
        
      </div>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>